import React from 'react'
import "./D.css"
const D0 = () => {
  return (
    <div className='main'>
<div id="leftmenu">
  <h1 align="center" class="style20">&nbsp;</h1>
  <div align="justify" class="style1">
    <p align="center"><a name="introduction" id="introduction"></a>THE FAITH   OF THE CHURCH </p>
  </div>
  <p align="center"><strong>PART-I</strong></p>
  <p align="justify"><strong>Introduction</strong><br></br>
    A member of the Oriental   Orthodox family of Churches, the Church of Ethiopia shares with them in essence   a common faith. This faith, the churches believes, is derived from the apostolic   heritage and borne witness to in the New Testament against the background of the   Old Testament. It has been expounded by the fathers of the Church both in the   ancient councils and in their teaching. It continues as a living reality in the   church in its life of worship, preaching and discipline. In a word, then in the   church of Ethiopia is a community which has inherited and which holds to the   historic Christian faith as it has been handed down through the centuries. What   is attempted here is, only to give a brief introduction to the faith of the   Church of Ethiopia. (1) </p>
  <p align="justify">&nbsp;</p>
  <p align="justify"><strong><a name="trinity" id="trinity"></a>The Mystery of the   Holy Trinity</strong><br></br>
    God is the only eternal Being. Beyond time, space and   all limitations, He abides without a beginning and without an end. “Thou hast no   beginning,” says in prayer the Ethiopian priest who celebrates the Anaphora of   St. John, “but Thou bringest all things to their end. Infinite art Thou, but for   all things Thou didst set bounds.”<br></br>
    <br></br>
    God is the Creator of all that exists.   Having made them all, He continues to sustain them. The Lord is high, says the   Anaphora. Yet “all were created through His grace, and all live through His   kindness”. Perfect in Himself, He continually imparts perfection to His   creatures. Individuals as well as the entire historical process are ultimately   under His control. God is not a passive perfection or an abstract ideal, but a   dynamic reality who is ever active in bringing all that exists to the final   destiny which He has for each of them as well as for the whole created realm. <br></br>
    <br></br>
    God is one in three and three in one. The unity of God is nor convinced   in the sense of an arithmetical digit nor of a solitary condition, but in that   of an all-inclusive perfection. So the one is also eternally three. He is,   affirms the Anaphora, “three names and one God, three prosopa and one   appearance, three persons and one essence”. <br></br>
    <br></br>
    The unity of God is   confessed as the unity of Godhead – Melekote as the word is used in Ethiopia.   The one Godhead is shared equally and eternally by the three Persons – Akal as   they are referred to in Ethiopia. As in other parts of the Christian world, in   Ethiopia also there were men who tried to interpret the doctrine in various   ways. there were, for instance, persons who refused to accept the personal   distinctions in the one Godhead and others who insisted that the three Persons   were three Gods. Both these views were rejected by the Church.<br></br>
    <br></br>
    God is   eternally Father, eternally Son, and eternally Holy Spirit. “The Father beget   His son without days or hours; and when He beget Him, His Father was not   separated from Him.” Beyond time, God is the eternal One. That One is Father,   Son and Holy Spirit. No one of the three Persons is prior to the other two in   time. “The One was not before the Other”, says the Anaphora, “and the Second was   not before the Third.” But “we proclaim that the Father lived with His Son, and   that the Son lived with His Father before creation, and before the heavens and   the earth were made.”<br></br>
    <br></br>
    In the one co-eternal and co-equal Trinity, the   Father is the eternal source if the Son and the Holy Spirit. The Son is born of,   and the Holy Spirit proceeds from, the Father. While affirming that the Son and   the Holy Spirit derive each of them His respective being eternally from the   Father, it is insisted that “the Father did not beget the Son to help Him in His   work before the world was created and the existence of the Holy Spirit is not to   contribute wisdom and work.”<br></br>
    <br></br>
    It is not with the Deity as it was with   Abraham who was older than Isaac. Or with Isaac who was older than Jacob, but   the Father is not older than the Son, neither is the Son older than the Holy   Spirit, and the Holy Spirit is not younger than the Son, neither is the Son   younger than His Father.<br></br>
    <br></br>
    The Father is different from the Son and the   Holy Spirit only in that He alone is Father. The Son alone is Son, and the Holy   Spirit alone dwells in us and makes God known to us. So the priest who   celebrates the Anaphora of St. John says in prayer, “But thy living Holy Spirit   knoweth the depth of Thy Godhead. He has declared to us Thy nature, and told us   about Thy oneness. He taught thy unity, and helped to know Thy Trinity.” The one   Godhead is, therefore, in the Father in perfection. Form Him the same Godhead is   received in perfection by the Son through His eternal generation; and from the   Father again the same Godhead in perfection is derived eternally by the Holy   Spirit. It is affirmed at the same time with equal force that “the father is not   grater than the Son, and the Son is not less than His Father,” and the Holy   Spirit in not grater or less than either the Father or Son. Thus the unity of   God is affirmed by confessing that the Godhead is one, and that the Godhead is   eternally in the Father. The Son and the Holy Spirit receive the same Godhead   eternally and in perfection from the Father.<br></br>
    <br></br>
    There is also another   equally important emphasis regarding divine unity. This lies in the affirmation   that the Father, the Son and the Holy Spirit are eternally inseparably together.   In everything that the Father does, the Son and the Holy Spirit are there with   Him; in all the things that the Son does, the Father and the Holy Spirit are   there with Him; and in all activities of the Holy Spirit, the Father and the Son   are also with him. It is affirmed that “the father, being Father, doth not give   orders to the Son; and the Son, being Son, is not exalted; and the Holy Spirit   is equal. Both the divine Father, Son and Holy Spirit is equal. But the divine   Father, Son and Holy Spirit and are one God, one Kingdom, one authority and one   government.”<br></br>
    <br></br>
    If we may put the emphasis in our words, the term “Father”   with reference to God signifies the divine reality which originates everything;   the Son indicates the divine reality implying all that is originated; and the   Holy Spirit signifies the divine reality which dwells in creatures relating them   both individually and corporately to God. The eternal God, as we have noted   already, is the all-inclusive perfection. He creates all things; He sustains   them; and He guides them to a final destiny.<br></br>
    <br></br>
    Infinite love, God creates   and sustains the world and all that there is in it. It is God the Father who   bring all this into being; but it is accomplished in reality through the Son,   and is perfected in the Holy Spirit. All this is one activity of God consisting   of different aspects. Grounded in the Son and upheld and perfected by the Holy   Spirit, the created world belongs to the Father. In His love God the Father sent   His only Son into the world in order to accomplish its salvation; in the same   love God the Son came and worked out the world’s salvation; in the same love   again God the Holy Spirit perfects the salvation thus given. All these are   manifestation at different levels of the same activity of God in relation to the   world. (1)</p>
  <p align="justify"><strong><a href="http://www.copticchurch.net/topics/theology/The_Meaning_of_the_Holy_Trinity_fr_abraam_sleman.pdf">The   meaning of Holy Trinity</a> (Pope Shenouda III)</strong></p>
  <p align="justify">&nbsp;</p>
  <p align="justify"><strong><a name="incarnation" id="incarnation"></a>The Mystery of   the Incarnation </strong><br></br>
    The incarnation of God the Son is primarily for the   salvation of the world. Salvation means to restoration of the world to its   direct and unimpeded relation with God.<br></br>
    <br></br>
    As God made it, the world was   very good. But evil came there in it. God who made the world is ever concerned   and active to save it from the clutches of evil and restore it to the destiny   for which it has been created. Incarnation is God’s supreme act in saving the   world. <br></br>
    <br></br>
    God the Son entered the earthly realm of existence in a unique   way by taking over Himself a perfectly real human life. This is incarnation by   which God the Father who created the world through God the Son and perfects it   through God the Holy Spirit, manifests through the Son His saving work for the   world and completes it in the Holy Spirit. As creation is the work of God,   redemption is also God’s work.<br></br>
    <br></br>
    God who created the world made man as the   crown of creation. Made in God’s image and endowed with creaturely freedom and   autonomy, man seeks God and reflects on His being and nature. Through the wrong   exercise of man’s freewill there came on him and the world at large misery and   suffering as well as sin and evil. The salvation of the wold, therefore,   required pre-eminently the healing of man. It is this healing which the   Incarnation is believed by the Church to have aimed to accomplish.<br></br>
    <br></br>
    In the   Incarnation, God the Son united to Himself real and perfects manhood. Conceived   in her womb by Mary the Virgin through the work of the Holy Spirit, He was born   in the world as a real man. At the very moment of His conception, through the   operation of the Holy Spirit, a personal manhood was formed in the Virgin’s womb   in union with God the Son. Thus God the Son united to Himself the manhood taken   from the human mother and was born as perfect God and perfect man in the real   sense. <br></br>
    <br></br>
    Jesus Christ, the incarnate God the Son, is one Person,   continuous with Godhead and continuous with manhood. In Him Godhead and manhood   continue each in its integrity and perfection, in a state of indivisible and   unconfused union.</p>
  <p align="justify">On this ground the Church of Ethiopia, with the other Oriental   Orthodox Churches, affirms that Jesus Christ is not two natures, but one   incarnate nature of God the Word. The “one” here is not meant to ignore the   dynamic continuance of either Godhead or manhood in the one Christ, but to   confess a real incarnation whereby God the Son entered the world of ours as a   man. He is indeed God the incarnate Son even while He is found to undergo the   frailty of manhood. <br></br>
      <br></br>
    Living as He did a life of unbroken communion with   God, He was absolutely sinless. Maintaining this union in the most inward and   real sense, He entered into our battle with sin and evil as a man, and fell a   victim to our death. By His suffering and ignominious death on the cross He   scored a victory over the forces of evil, and by His resurrection from the dead   He lives eternally in His natural unity with God the Father and God the Holy   Spirit, and in his unbroken and indivisible union with the manhood. In Jesus   Christ, then, we have the incarnate, crucified and glorified God the Son, who is   Himself our brother, signifying the final destiny awaiting the human   race.<br></br>
    <br></br>
    Regarding the Person of Jesus Christ also there have been serious   discussions in Ethiopia. But the Church holds to the view that He is God the Son   in His incarnate state. Born of God the Father eternally as God the Son, He was   born of the Virgin Mother as a real man. There are a number of affirmations in   the Anaphora regarding Him, some of which may be noted here.</p>
  <p align="justify">1.Jesus Christ was born of Our Lady Mary for our salvation. He   who does not believe in His birth from Holy Mary, let him be anathema.</p>
  <p align="justify">2. In this way, after being conceived in the womb of the   Virgin, God the Son was born as a man. By His conception, God the Son became   incarnate “taking our nature.” The Son who is born of the Father without a   mother, was born as a man without a Father. “He put on mortal flesh and made it   immortal,” and He came truly into the world “clothed in the body which He took   from us.”</p>
  <p align="justify">3. His human birth was a unique event, whereby God the Son   “came down through the will of His Father” and was made man. “His humanity was   not inferior because He had no Father to be born of His seed.” This is   incarnation, whereby God the Son entered the historical realm in order to save   it forever.</p>
  <p align="justify">4. In the Incarnation, God the Son united to Himself manhood   and “made it one with his Godhead without mixture or confusion, without division   or alternation.” Therefore, “His Godhead was not separated from His manhood, not   for an hour, nor for the twinkling of an eye.”</p>
  <p align="justify">5. God the Son came to us “without being separated from His   Godhead.” After being born, “He grew like an infant, and grew little by little   until He matured like a man. At the age of thirty He was baptized in the   Jordan.” He was tempted by the devil; “He hungered and thirsted,” He went about   “preaching the gospel of the kingdom of Heaven.” By this, who is perfect like   God the Father and is His image walked among us in our image.</p>
  <p align="justify">6. He suffered passion and death voluntarily on our behalf and   for our sakes. He became hungry as man, and granted food to many with very   little bread. He thirsted as a man who dies, but changed water into wine as   being able to give life to all.<br></br>
      <br></br>
    They bet Him on the head as a servant and   He set free from the yoke of sin as Lord of all. He suffered all. He cured the   blind with His spittle and gave us the Holy Spirit by receiving the spittle of   the unclean. He who forgiveth sin was accused as a sinner by them. The judge of   judges was judges by them. He was crucified on the tree to destroy sin, was   crucified with the sinner to control with the righteous. He died through His   will, and was buried willingly; He died to destroy death, He died to give life   to the dead; He was buried to raise those who were buried, to keep the living,   to justify the impure, to justify the sinners, to gather together those who were   scattered, and to turn the sinners to glory and honour.<br></br>
    <br></br>
    Such passages in   the Anaphora are too numerous to be reproduced or even noted in the present   context. They show that Jesus Christ was at once God and man without division or   confusion. The same Christ, God the Son incarnate, expressed the divine actions   as well as the human. He is one Christ, in whom God and man are indivisibly   united.</p>
  <p align="justify">7. As to the absolute reality of the suffering and death, there   are passages almost without number. We shall reproduce here two of them, one   taken from the Anaphora of St. James of Serug, and the other from the Anaphora   of St. Dioscorus. The priest who celebrates using the first of these two   Anaphora’s says in prayer:<br></br>
      <br></br>
    O Lord, Thou wast struck with the hands of a   servant, beaten with sticks, pierced with a spear, and they caused Thee to drink   a little gall with vinegar. While Thou was God able to prevent them, thou didst   not prevent them, Thou didst become patient even to death; all this thou didst   accept for the love of man.<br></br>
    <br></br>
    The Anaphora of St. Dioscorus contains the   following passages bearing on the point at issue in the present context. The   priest says there in prayer: <br></br>
    <br></br>
    He was laid in the manger of the cattle,   received the presents of His kingdom, and wept as infants do, asking for food   from the breast of His mother. As to suffering and death in particular, we have   passages like the following. They crucified Him on the tree, nailed him with   nails, beat Him on the head with sticks, pierced his side with a spear, to Him   who gave drink to the Israelites from a rock they gave to drink gall mixed with   myrrh in His thirst. The immortal died, died to destroy death, died to quicken   the dead as He promised them with the word of covenant.</p>
  <p align="justify">8. Death was not the end of His dispensation. “He rose from the   dead, absolutely without corruption and set is free from the yoke of sin.” The   risen Christ ascended into heaven and is with God the Father. He has triumphed   over death and decay.<br></br>
      <br></br>
    These and the many other passages in the Liturgy   show that the manhood of Christ was absolutely real and perfect. But everywhere   the emphasis is on the unity of Jesus Christ. It is affirmed that He is God the   Son in His incarnate state. As regards the Incarnation, it is clearly shown that   He was conceived in the Virgin’s womb, and that He was born as a real man. At   the very moment of His conception, through the Holy Spirit, actual manhood was   formed from the human mother in union with Himself. It is to Him who was thus   conceived that the Virgin gave birth. Therefore, Jesus Christ is indivisibly   one. The two natures of Godhead and manhood which came into union in Him   continue in the one Christ, each in its absolute integrity and perfection with   its respective properties, without change or division. Each of them continues in   its dynamic reality, not in a quiescent state, so that Christ is God and man at   the same time.<br></br>
    <br></br>
    The Church of Ethiopia, with the other Oriental Orthodox   Churches, has refused to accept the Chalcedonian Definition of the Faith with   the affirmation that Christ is “made known in two natures.” If by the expression   the Churches which accept the Definition mean only that Godhead and manhood   continue in the one Chris dynamically, this is the teaching of the Ethiopian   Orthodox Church. On the other hand, if the expression is taken in the sense that   Godhead and manhood continue in Christ only in a state of moral union, there is   a basic difference on this issue between the churches of the Chalcedonian   tradition and the Church of Ethiopia, which should be noted. (1)</p>
  <p align="justify"><a href="http://www.copticchurch.net/topics/theology/incarnation_st_athanasius.pdf"><strong>The   Incarnation (St. Athnasius)</strong></a></p>
  <p align="justify"><br></br>
      <strong><a name="baptisim" id="baptisim"></a>The Mystery of   Baptism</strong><br></br>
    “He who believes and is baptized will be saved; but he who   does not believe will be condemned.” (Mk. 16:6). Truly, truly, I say to you,   unless one is born of water and the spirit he can not enter the kingdom of God.”   (John 3:5).</p>
  <p align="justify">In accordance with such writings of the Holy Scriptures, the   Ethiopian Orthodox Tewahido Church baptizes male infants at the age of 40 days   and female infants at the age of 80 days, (Lev. 12:2-7). Yet if an infant is   sick, so that the infant may not die before being baptized and be subjected to   the unchangeable order of the Lord Jesus Christ, “unless one is born of water   and the spirit he can not enter the kingdom of God”, the Ethiopian Orthodox   Tewahido Church baptizes infants just as they come even prior to the above fixed   baptismal dates. In addition, if an adult believes and requests baptism, the   Ethiopian Orthodox Tewahido Church willingly complies and baptizes him or her. </p>
  <p align="justify">&nbsp;</p>
  <p align="justify"><strong>Few words from the Holy Scriptures that testify   Baptism</strong></p>
  <p align="justify">“Go therefore and make disciples of all nations, baptizing them   in the name of the Father and of the Son and of the Holy Spirit” (Mt. 28:19).   And Peter said to them, “Repent, and be baptized everyone of you in the name of   the Jesus Christ for the forgiveness of your sins; and you shall receive the   gift of the Holy Spirit” (Acts. 2:38). “And he commanded them to be baptized in   the name of Jesus Christ” (Acts. 10:48). “Do you not know that all of us who   have been baptized into His death “ (Rome 6:3). “For by one Spirit we were all   baptized into one body – Jews or Greeks, slaves or free- and all were made to   drink of one spirit” (1 Cor. 12:13). “Baptism, which corresponds to this, now   saves us (you), not as a removal of dirt from the body but as an appeal to God   for a clear conscience…” (1 Pet. 3:12). Such words testify to the usefulness of   our Baptism. (2)</p>
  <p align="justify">&nbsp;</p>
  <p align="justify"><strong><a name="communion" id="communion"></a>The Mystery of the   Holy Communion; what is Holy Communion?</strong></p>
  <p align="justify">It is a sacrament through which we are far off from the   domination of sin and get nearer of attain to communion with God. It originates   from the rites conducted by the children of Israel when they attained their   freedom from the bondage of slavery and so killed a ritual sheep and sprinkled   its blood on the door posts to protect themselves from sudden death and   destruction. Based on this example, Jesus Christ, who is the Lamb of God, who   takes away the sin of the world has founded the Mystery of the Holy Communion by   offering. Himself as a true sacrifice on the cross. (Ex. 5-15 Isa. 53: 7 Jn.   1:29). “For the law made nothing perfect; on the other hand, a better hope is   introduced, through which we draw near to God,” (Heb. 7:19)</p>
  <p align="justify">&nbsp;</p>
  <p align="justify">The Preparation and Presentation of the Holy Communion is in   the form of bread and wine; i.e. like that of Melchizedek, King of Salem’s   presentation to Abraham (Gen. 14:18). Why the Holy Communion is called Mystery   is that by partaking of the visible Bread and Wine, we attain to invisible   heavenly blessings and eternal life. “…Truly, truly, I say to you, unless you   eat the flesh of the Son of man and drink His blood, you have no life in you; he   who eats my flesh and drinks my blood has eternal life, and I will raise him up   at the last day. For my flesh is food indeed, and my blood is drink indeed. He   who eats my flesh and drinks my blood abides in Me; and I in him,” (Jn. 6:   53-57). “Whoever, therefore, eats the bread of drinks the cup of the Lord in an   unworthy manner, (will be examined by the Blessed Holy Trinity of being   unworthy) and will be guilty of profaning the body and blood of the Lord. Let a   man examine himself, and so eat of the Bread and drink of the Cup. For any one   who eats and drinks without discerning the body, eats and drinks judgment upon   himself. That is why many of you are weak and ill, and some have died. But if we   judged ourselves truly, we should not be judged’ (1 Cor. 11:27-32). It is,   therefore, based on this teaching that the Ethiopian Orthodox Tewahido Church   calls upon her followers to be pure from sin, reveille strange thoughts,   fornication etc. and to receive the true flesh and blood of our Lord Jesus   Christ who was crucified upon the cross on Holy Friday for the salvation of the   world.</p>
  <p align="justify">The priest when putting the bread on the plate and the wine in   the cup (chalice) blesses them. During the service of the Holy Liturgy, the   bread turns into the true flesh of the Son of God and the wine into the true   blood of the Son of God. Athanasius said, “we believe that the bread and wine   before the priest blesses them are simple bread and wine, but after the blessing   they are truly turned into the flesh and the blood of the Son of God,   “Therefore, what the Apostles received on the night of Good Thursday, and what   has been sacrificed upon the cross on Good Friday, and what is still being   offered today and to the end of the world in the four corners of the world is   one band the same. St. John of Chrysostom said that, the poor sacrifice which   the priests offer every time is one and the same sacrifice, which has been   offered upon the cross.</p>
  <p align="justify">&nbsp;</p>
  <p align="justify">He (St. John) also confirms that it is not a symbol, but the   real and blood of the Son of God.</p>
  <p align="justify">Supporting scriptural words about the teaching Of the Holy   Communion “Now as they were eating, Jesus took bread, and blessed, and broke it,   and gave it to the disciples and said, take, cat; this is my Body. And He took a   cup, and when He had given thanks He gave it to them, saying, drink of it, all   of you; for this is my Blood of the covenant, which is poured out for many for   the forgiveness of sins,” (Mt. 26: 26-29; Mk, 14: 22; Lk. 22: 19). “Truly truly,   I say to you, it was not Moses who gave you the bread from heaven. For the bread   of God is that which comes down from heaven, and gives life to the world” (Jn.   6: 32; 35; 51-59), such passages confirm the doctrine of the Holy Communion.   (2)</p>
  <p align="justify"><br></br>
      <strong><a name="resurrection" id="resurrection"></a>The   Mystery of the Resurrection</strong></p>
  <p align="justify">“Do not marvel at this; for the hour is coming when all who are   in the combs will hear His voice and come forth, those who have done good, to   the resurrection of life and those who have done evil, to the resurrection of   judgment” (Jn. 5: 28-29). St. Paul said. “There is one glory of the Sun, and   another glory of the moon, and another glory of the stars; for star differs from   star in glory. So it is with the resurrection of the dead. (1 Cor. 15:   41-42).</p>
  <p align="justify">&nbsp;</p>
  <p align="justify">Supporting Scriptural Words Concerning the Resurrection</p>
  <p align="justify">“ For this is the will of my Father, that everyone who sees the   son and believes in Him should have eternal life; and I will raise him up at the   last day” (Jn. 5: 25, 6: 40, 11:25) “ Knowing that he who raised the Lord Jesus   will raise us also with Jesus and bring us with you into His presence” (2 Cor.   4:14). “ For the Lord Himself will descend from heaven with a cry of command,   with the archangel’s call; and with the sound of the trumpet of God. And the   dead in Christ will rise first,” (1 Thess. 4:16). “Having a hope in God which   these themselves accept that there will be a resurrection of both the just and   the unjust. “ (Acts 24: 15, Dan. 12: 2). The Resurrection of those already   raised in the Scripture is an evidence of our Resurrection.</p>
  <p align="justify">Elijah raised one child (1 Kg. 17: 21-22) Elisha raised the Son   of the Shunammite (2 Kg 4:35) a dead man raised on the touch of the bone of   Elisha (2 Kg. 13: 21).</p>
  <p align="justify">A daughter of a ruler was raised by the Lord (Mt. 9: 25). The   dead who were raised on the crucification day of the Lord. (Mt. 27:52) </p>
  <p align="justify">The Son of a widow at Nail was raised by the Lord (Lk.   7:15).</p>
  <p align="justify">The raising of Lazarus at Bethany by the Lord (Jn. 11:   43-44)</p>
  <p align="justify">Dorcas was raised by Peter (Acts 9: 40) .</p>
  <p align="justify">The bodily living (life) of Enoch and Elijah is one indication   of our resurrected eternal life. But our fundamental understanding of our   raising is the Resurrection of Jesus Christ. As Amoniyos and Awsabeyos stated in   the introduction of the Gospel, “He is risen so as to teach the Resurrection, of   our bodies”</p>
  <p align="justify">Based on the above teachings, the Ethiopian Orthodox Tewahido   Church offers belief and worships the High God who creates and rules. In this   teaching, our church is in accordance with the ancient churches; such as   Alexandrian, Syrian, Armenian, and Indian Orthodox Churches. (2)</p>
  <p align="justify">&nbsp;</p>
  <p align="justify"><strong><a name="salvation" id="salvation"></a>Human   Salvation</strong><br></br>
    The Incarnation is first and foremost for the salvation of   the world, The salvation of the world means pre-eminently the redemption of the   human race. The saving work of God accomplished through the Incarnation is to be   appropriated by man, both individually and corporately. It is when this is done   with reference to the entire human race that the work of salvation of the world   will have been perfected. God Himself is carrying on this work through the Holy   Spirit.<br></br>
    <br></br>
    In his life and existence man includes both the individual and   the corporate dimensions. The saving work accomplished by God in the Incarnation   should, therefore, be assimilated and perfected in both these dimensions. It is   to carry on this divine work that the Church is founded by God. The incarnate,   crucified and risen Christ is in the Church, which is His body on earth, through   the Holy Spirit.<br></br>
    <br></br>
    The Holy Spirit works in the Church through individual   members as well as its community as a corporate body, in order to make the   saving activity of God real to them. This is done through the various ministries   of the Sacraments, preaching and teaching. In this way individual persons are   inspired to dedicate their lives, and both individuals and communities are   guided to carry forward the ministry of Jesus Christ in the social, economic,   political and such other spheres of human life for the well-being of man and the   world at large.<br></br>
    <br></br>
    This concern is giving expression to in the Anaphora’s of   the Church of Ethiopia by including prayers for all these areas of life in the   world. Thus prayers are offered for rains, that God may send them where they are   needed; for waters of the rivers, that “God should fill them unto their due   measure and bounds”; for the fruits of the earth, that “God may grant to the   earth her fruit for sowing and for harvest”; and for the prevailing of the   spirit of peace for the people. In the same way every liturgical celebration   includes intercession for the Emperor as the Head of the State and for   ecclesiastical leaders. Besides, traders, farmers and craftsmen, as well as   those in need, sickness or oppression are specially remembered. Prayers are also   offered for those who have fallen in any manner of sin. All these show that the   entire realm of nature and all conditions of men and women are committed to   divine protection and care at every service of worship.<br></br>
    <br></br>
    The Christian’s   ultimate concern in life is not understood in terms merely of the hope for a   blessed life in the world to come. On the other hand, this world itself is   affirmed to belong to God. But the fact of evil in it is admitted, both in the   natural realm and in the moral realm. Salvation is a present experience   consisting in man’s complete confidence and communion with God as well as his   perfect peace and harmony with his fellow beings. This sate of being which   should be ours here and now should grow till it reaches its final culmination in   the eternal realm. Thus salvation is a present reality which has a future   reference. The Church has the responsibility to inspire its member to work for   the well being of life in the world here and now and to proclaim the hope of   eternal life in the world to come.<br></br>
    <br></br>
    In this world man is entitled to   individual freedom, social justice, economic sufficiency and such other rights   as will enable him to develop his talents for the good of himself and of others.   The Church as a body should stand for the realization of these rights. However,   the Church of Ethiopia does not agree with the view that the Christian’s concern   is only to work for the welfare of man in this world. This world and our lives   in it are nothing but transitory. No man can be absolutely sure of what will   happen to him tomorrow. Furthermore, material prosperity does not as a rule lead   to peaceful life, either for the individual or for peoples and notions. In any   case, the Church of Ethiopia does not think that its mission is to build up   exclusively a city in this world. The hope in the life of the world to come is   an integral part of its faith.<br></br>
    <br></br>
    The Apostolic Creed which is in use in the   Church of Ethiopia has three sections bearing on our discussion in the present   context. The first of them insists that “all creatures of God are good and there   is nothing to be rejected, and the spirit, the life of the body, is pure and   holy in all.” The entire natural realm has been made pure and holy by God and   all that is for man’s regular use. The second passage affirms that “marriage is   pure, and childbirth is undefiled, because God created Adam and Eve to   multiply.” This is a clear statement which shows that in the faith of the Church   of Ethiopia, human society is of divine creation, so that the social, economic   political and other such ties of man are divinely instituted. In the third   passage there is the confession that we “believe in the resurrection of the   dead, the righteous and sinners; and in the Day of Judgment when everyone will   be recompensed according to his deeds.” This statement affirms the   eschatological hope in the Church’s faith.<br></br>
    <br></br>
    Putting the three ideas   together, we can say that according to the faith of the Church of Ethiopia, the   natural realm has been created by God, who has Himself placed man in the world   as a member of society. There is a destiny awaiting man, and that is to be   attained by him in the risen life in the world to come. In the face of evil and   sin in this world of our God has worked out man’s salvation through His   incarnate Son, who rose from the dead and lives eternally offering us the   assurance of a resurrection that will be ours also. (1)</p>
  <p align="justify">&nbsp;</p>
  <p align="justify"><strong><a name="conclusion" id="conclusion"></a>A word in   conclusion</strong><br></br>
    The eternal and triune God who is beyond time and space   has created the world in time and space. He has redeemed the world and continues   His work of perfecting the saving act. The salvation was accomplished by God   through the suffering, death and resurrection of His incarnate Son and is   perfected through His Holy Spirit.<br></br>
    <br></br>
    In is this saving work of God that is   represented in every celebration of the Holy Eucharist, which is not merely a   memorial service to commemorate the death and resurrection of Jesus Christ. But   in it the Church offers itself and the whole-redeemed human race together with   the natural realm of earthly existence to the triune God. This is why in the   celebration of the Holy Eucharist, as also in its various other acts of worship,   the Church calls to remembrance the living and the departed sections of the   communion of saints. This is done in the context of remembering the saving acts   of God, not merely as past events, but as events which happened actually in the   realm of history and which signify the continuous work of God for the salvation   of the world. The Service of the Holy Eucharist brings to us above all the   assurance of the eschatological dimension of the Christian faith.</p>
  <p align="justify"><br></br>
    We proclaim Thy death, Lord and Thy holy resurrection, we   believe in Thine ascension and Thy second coming, we glorify Thee, we offer our   prayer unto Thee and supplicate Thee our Lord and our God.</p>
  <p align="justify">Grant us, Lord, to do Thy will and Thy good pleasure at all   times, and write our names in the book if life in the kingdom of heaven with all   saints and martyrs, though Jesus Christ our Lord, though whom, to Thee, with Him   and with the Holy Spirit be glory and dominion, both now and ever and world   without end.<br></br>
    Amen. (1)</p>
  <p align="justify"><br></br>
    <span class="style2 style3 style4 style5"><br></br>
    (1) Written by V C Samuel <br></br>
“THE CHURCH OF   ETHIOPIA A PANORAMA OF HISTORY AND SPIRITUAL LIFE” <br></br>
Addis Ababa –December   1970. A publication of the EOTC</span></p>
  <p align="justify" class="style2 style3 style4 style5"><br></br>
    (2) A short History, Faith and Order of The Ethiopian   Orthodox Church, published by the Ethiopian Orthodox Tewahedo Church Holy Synod,   Addis Ababa 1983.</p>
  <p align="justify" class="style2 style3 style4 style5">&nbsp;</p>
  <p align="justify"><strong><a href="http://www.copticchurch.net/topics/theology/divinity_of_christ_pope_shenouda.pdf">The   Divinity of Christ</a> (Pope Shenouda III)</strong></p>
  <p align="justify"><strong><a href="http://www.copticchurch.net/topics/theology/nature_of_christ.pdf">The   Nature of Christ</a> <strong>(Pope Shenouda III)</strong></strong></p>
  <p align="justify"><strong><a href="http://www.copticchurch.net/topics/theology/comptheo.pdf">Comparative   Theology </a><strong>(Pope Shenouda III)</strong></strong></p>
  <p>&nbsp;</p>
  <p align="center">&nbsp;</p>
  <p align="center">&nbsp;</p>
  <p></p>
</div>
    </div>
  )
}

export default D0
